[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENABLEGITINFO = "false"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "https://brenda.moon.net.au/*"
  to = "https://moon.net.au/:splat"
  status = 301
  force = true
